project_id = "bhsnjbisxeuguhggjyzv"

[auth]
enabled = true

[functions.chat-with-sam]
verify_jwt = false

[functions.chat-with-creekside]
verify_jwt = false

[functions.detect-territory]
verify_jwt = false